name: moolax
description: "Moola X: A foreign currency converter for travelers"
version: 3.0.0+2

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.0

flutter:
  uses-material-design: true
