name: moolax
description: "Moola X: A foreign currency converter for travelers"
version: 3.0.0+3

environment:
  sdk: ^3.0.0

dependencies:
  connectivity_plus: ^6.0.2
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  http: ^1.2.1
  purchases_flutter: ^6.26.0
  shared_preferences: ^2.2.3
  in_app_purchases_paywall_ui: ^1.0.1 

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
