name: moolax
description: "Moola X: A foreign currency converter for travelers"
version: 3.0.0+3

environment:
  sdk: ^3.0.0

dependencies:
  connectivity_plus: ^4.0.1
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
