/*
 * Copyright (c) 2019 Razeware LLC
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * Notwithstanding the foregoing, you may not use, copy, modify, merge, publish,
 * distribute, sublicense, create a derivative work, and/or sell copies of the
 * Software in any work that is designed, intended, or marketed for pedagogical or
 * instructional purposes related to programming, coding, application development,
 * or information technology.  Permission for such use, copying, modification,
 * merger, publication, distribution, sublicensing, creation of derivative works,
 * or sale is expressly withheld.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

class IsoData {
  static flagOf(String code) {
    return data[code]['flag'] ?? '?';
  }

  static longNameOf(String code) {

    return data[code]['name'] ?? 'unknown name';
  }

  static final Map<String, Map<String, String>> data = {
    'AED': {'name': 'UAE Dirham', 'flag': 'xxx'},
    'AFN': {'name': 'Afghani', 'flag': 'xxx'},
    'ALL': {'name': 'Lek', 'flag': 'xxx'},
    'AMD': {'name': 'Armenian Dram', 'flag': 'xxx'},
    'ANG': {'name': 'Netherlands Antillean Guilder', 'flag': 'xxx'},
    'AOA': {'name': 'Kwanza', 'flag': 'xxx'},
    'ARS': {'name': 'Argentine Peso', 'flag': 'xxx'},
    'AUD': {'name': 'Australian Dollar', 'flag': '🇦🇺'},
    'AWG': {'name': 'Aruban Florin', 'flag': 'xxx'},
    'AZN': {'name': 'Azerbaijan Manat', 'flag': 'xxx'},
    'BAM': {'name': 'Convertible Mark', 'flag': 'xxx'},
    'BBD': {'name': 'Barbados Dollar', 'flag': 'xxx'},
    'BDT': {'name': 'Taka', 'flag': 'xxx'},
    'BGN': {'name': 'Bulgarian Lev', 'flag': '🇧🇬'},
    'BHD': {'name': 'Bahraini Dinar', 'flag': 'xxx'},
    'BIF': {'name': 'Burundi Franc', 'flag': 'xxx'},
    'BMD': {'name': 'Bermudian Dollar', 'flag': 'xxx'},
    'BND': {'name': 'Brunei Dollar', 'flag': 'xxx'},
    'BOB': {'name': 'Boliviano', 'flag': 'xxx'},
    'BOV': {'name': 'Mvdol', 'flag': 'xxx'},
    'BRL': {'name': 'Brazilian Real', 'flag': '🇧🇷'},
    'BSD': {'name': 'Bahamian Dollar', 'flag': 'xxx'},
    'BTN': {'name': 'Ngultrum', 'flag': 'xxx'},
    'BWP': {'name': 'Pula', 'flag': 'xxx'},
    'BYN': {'name': 'Belarusian Ruble', 'flag': 'xxx'},
    'BZD': {'name': 'Belize Dollar', 'flag': 'xxx'},
    'CAD': {'name': 'Canadian Dollar', 'flag': '🇨🇦'},
    'CDF': {'name': 'Congolese Franc', 'flag': 'xxx'},
    'CHE': {'name': 'WIR Euro', 'flag': 'xxx'},
    'CHF': {'name': 'Swiss Franc', 'flag': '🇨🇭'},
    'CHW': {'name': 'WIR Franc', 'flag': 'xxx'},
    'CLF': {'name': 'Unidad de Fomento', 'flag': 'xxx'},
    'CLP': {'name': 'Chilean Peso', 'flag': 'xxx'},
    'CNY': {'name': 'Yuan Renminbi', 'flag': '🇨🇳'},
    'COP': {'name': 'Colombian Peso', 'flag': 'xxx'},
    'COU': {'name': 'Unidad de Valor Real', 'flag': 'xxx'},
    'CRC': {'name': 'Costa Rican Colon', 'flag': 'xxx'},
    'CUC': {'name': 'Peso Convertible', 'flag': 'xxx'},
    'CUP': {'name': 'Cuban Peso', 'flag': 'xxx'},
    'CVE': {'name': 'Cabo Verde Escudo', 'flag': 'xxx'},
    'CZK': {'name': 'Czech Koruna', 'flag': '🇨🇿'},
    'DJF': {'name': 'Djibouti Franc', 'flag': 'xxx'},
    'DKK': {'name': 'Danish Krone', 'flag': '🇩🇰'},
    'DOP': {'name': 'Dominican Peso', 'flag': 'xxx'},
    'DZD': {'name': 'Algerian Dinar', 'flag': 'xxx'},
    'EGP': {'name': 'Egyptian Pound', 'flag': 'xxx'},
    'ERN': {'name': 'Nakfa', 'flag': 'xxx'},
    'ETB': {'name': 'Ethiopian Birr', 'flag': 'xxx'},
    'EUR': {'name': 'Euro', 'flag': '🇪🇺'},
    'FJD': {'name': 'Fiji Dollar', 'flag': 'xxx'},
    'FKP': {'name': 'Falkland Islands Pound', 'flag': 'xxx'},
    'GBP': {'name': 'Pound Sterling', 'flag': '🇬🇧'},
    'GEL': {'name': 'Lari', 'flag': 'xxx'},
    'GHS': {'name': 'Ghana Cedi', 'flag': 'xxx'},
    'GIP': {'name': 'Gibraltar Pound', 'flag': 'xxx'},
    'GMD': {'name': 'Dalasi', 'flag': 'xxx'},
    'GNF': {'name': 'Guinean Franc', 'flag': 'xxx'},
    'GTQ': {'name': 'Quetzal', 'flag': 'xxx'},
    'GYD': {'name': 'Guyana Dollar', 'flag': 'xxx'},
    'HKD': {'name': 'Hong Kong Dollar', 'flag': '🇭🇰'},
    'HNL': {'name': 'Lempira', 'flag': 'xxx'},
    'HRK': {'name': 'Kuna', 'flag': '🇭🇷'},
    'HTG': {'name': 'Gourde', 'flag': 'xxx'},
    'HUF': {'name': 'Forint', 'flag': '🇭🇺'},
    'IDR': {'name': 'Rupiah', 'flag': '🇮🇩'},
    'ILS': {'name': 'New Israeli Sheqel', 'flag': '🇮🇱'},
    'INR': {'name': 'Indian Rupee', 'flag': '🇮🇳'},
    'IQD': {'name': 'Iraqi Dinar', 'flag': 'xxx'},
    'IRR': {'name': 'Iranian Rial', 'flag': 'xxx'},
    'ISK': {'name': 'Iceland Krona', 'flag': '🇮🇸'},
    'JMD': {'name': 'Jamaican Dollar', 'flag': 'xxx'},
    'JOD': {'name': 'Jordanian Dinar', 'flag': 'xxx'},
    'JPY': {'name': 'Yen', 'flag': '🇯🇵'},
    'KES': {'name': 'Kenyan Shilling', 'flag': 'xxx'},
    'KGS': {'name': 'Som', 'flag': 'xxx'},
    'KHR': {'name': 'Riel', 'flag': 'xxx'},
    'KMF': {'name': 'Comorian Franc', 'flag': 'xxx'},
    'KPW': {'name': 'North Korean Won', 'flag': 'xxx'},
    'KRW': {'name': 'Won', 'flag': '🇰🇷'},
    'KWD': {'name': 'Kuwaiti Dinar', 'flag': 'xxx'},
    'KYD': {'name': 'Cayman Islands Dollar', 'flag': 'xxx'},
    'KZT': {'name': 'Tenge', 'flag': 'xxx'},
    'LAK': {'name': 'Lao Kip', 'flag': 'xxx'},
    'LBP': {'name': 'Lebanese Pound', 'flag': 'xxx'},
    'LKR': {'name': 'Sri Lanka Rupee', 'flag': 'xxx'},
    'LRD': {'name': 'Liberian Dollar', 'flag': 'xxx'},
    'LSL': {'name': 'Loti', 'flag': 'xxx'},
    'LYD': {'name': 'Libyan Dinar', 'flag': 'xxx'},
    'MAD': {'name': 'Moroccan Dirham', 'flag': 'xxx'},
    'MDL': {'name': 'Moldovan Leu', 'flag': 'xxx'},
    'MGA': {'name': 'Malagasy Ariary', 'flag': 'xxx'},
    'MKD': {'name': 'Denar', 'flag': 'xxx'},
    'MMK': {'name': 'Kyat', 'flag': 'xxx'},
    'MNT': {'name': 'Tugrik', 'flag': 'xxx'},
    'MOP': {'name': 'Pataca', 'flag': 'xxx'},
    'MRU': {'name': 'Ouguiya', 'flag': 'xxx'},
    'MUR': {'name': 'Mauritius Rupee', 'flag': 'xxx'},
    'MVR': {'name': 'Rufiyaa', 'flag': 'xxx'},
    'MWK': {'name': 'Malawi Kwacha', 'flag': 'xxx'},
    'MXN': {'name': 'Mexican Peso', 'flag': '🇲🇽'},
    'MXV': {'name': 'Mexican Unidad de Inversion (UDI)', 'flag': 'xxx'},
    'MYR': {'name': 'Malaysian Ringgit', 'flag': '🇲🇾'},
    'MZN': {'name': 'Mozambique Metical', 'flag': 'xxx'},
    'NAD': {'name': 'Namibia Dollar', 'flag': 'xxx'},
    'NGN': {'name': 'Naira', 'flag': 'xxx'},
    'NIO': {'name': 'Cordoba Oro', 'flag': 'xxx'},
    'NOK': {'name': 'Norwegian Krone', 'flag': '🇳🇴'},
    'NPR': {'name': 'Nepalese Rupee', 'flag': 'xxx'},
    'NZD': {'name': 'New Zealand Dollar', 'flag': '🇳🇿'},
    'OMR': {'name': 'Rial Omani', 'flag': 'xxx'},
    'PAB': {'name': 'Balboa', 'flag': 'xxx'},
    'PEN': {'name': 'Sol', 'flag': 'xxx'},
    'PGK': {'name': 'Kina', 'flag': 'xxx'},
    'PHP': {'name': 'Philippine Peso', 'flag': '🇵🇭'},
    'PKR': {'name': 'Pakistan Rupee', 'flag': 'xxx'},
    'PLN': {'name': 'Zloty', 'flag': '🇵🇱'},
    'PYG': {'name': 'Guarani', 'flag': 'xxx'},
    'QAR': {'name': 'Qatari Rial', 'flag': 'xxx'},
    'RON': {'name': 'Romanian Leu', 'flag': '🇷🇴'},
    'RSD': {'name': 'Serbian Dinar', 'flag': 'xxx'},
    'RUB': {'name': 'Russian Ruble', 'flag': '🇷🇺'},
    'RWF': {'name': 'Rwanda Franc', 'flag': 'xxx'},
    'SAR': {'name': 'Saudi Riyal', 'flag': 'xxx'},
    'SBD': {'name': 'Solomon Islands Dollar', 'flag': 'xxx'},
    'SCR': {'name': 'Seychelles Rupee', 'flag': 'xxx'},
    'SDG': {'name': 'Sudanese Pound', 'flag': 'xxx'},
    'SEK': {'name': 'Swedish Krona', 'flag': '🇸🇪'},
    'SGD': {'name': 'Singapore Dollar', 'flag': '🇸🇬'},
    'SHP': {'name': 'Saint Helena Pound', 'flag': 'xxx'},
    'SLL': {'name': 'Leone', 'flag': 'xxx'},
    'SOS': {'name': 'Somali Shilling', 'flag': 'xxx'},
    'SRD': {'name': 'Surinam Dollar', 'flag': 'xxx'},
    'SSP': {'name': 'South Sudanese Pound', 'flag': 'xxx'},
    'STN': {'name': 'Dobra', 'flag': 'xxx'},
    'SVC': {'name': 'El Salvador Colon', 'flag': 'xxx'},
    'SYP': {'name': 'Syrian Pound', 'flag': 'xxx'},
    'SZL': {'name': 'Lilangeni', 'flag': 'xxx'},
    'THB': {'name': 'Baht', 'flag': '🇹🇭'},
    'TJS': {'name': 'Somoni', 'flag': 'xxx'},
    'TMT': {'name': 'Turkmenistan New Manat', 'flag': 'xxx'},
    'TND': {'name': 'Tunisian Dinar', 'flag': 'xxx'},
    'TOP': {'name': 'Pa’anga', 'flag': 'xxx'},
    'TRY': {'name': 'Turkish Lira', 'flag': '🇹🇷'},
    'TTD': {'name': 'Trinidad and Tobago Dollar', 'flag': 'xxx'},
    'TWD': {'name': 'New Taiwan Dollar', 'flag': 'xxx'},
    'TZS': {'name': 'Tanzanian Shilling', 'flag': 'xxx'},
    'UAH': {'name': 'Hryvnia', 'flag': 'xxx'},
    'UGX': {'name': 'Uganda Shilling', 'flag': 'xxx'},
    'USD': {'name': 'US Dollar', 'flag': '🇺🇸'},
    'USN': {'name': 'US Dollar (Next day)', 'flag': 'xxx'},
    'UYI': {'name': 'Uruguay Peso en Unidades Indexadas (UI)', 'flag': 'xxx'},
    'UYU': {'name': 'Peso Uruguayo', 'flag': 'xxx'},
    'UYW': {'name': 'Unidad Previsional', 'flag': 'xxx'},
    'UZS': {'name': 'Uzbekistan Sum', 'flag': 'xxx'},
    'VES': {'name': 'Bolívar Soberano', 'flag': 'xxx'},
    'VND': {'name': 'Dong', 'flag': 'xxx'},
    'VUV': {'name': 'Vatu', 'flag': 'xxx'},
    'WST': {'name': 'Tala', 'flag': 'xxx'},
    'XAF': {'name': 'CFA Franc BEAC', 'flag': 'xxx'},
    'XAG': {'name': 'Silver', 'flag': 'xxx'},
    'XAU': {'name': 'Gold', 'flag': 'xxx'},
    'XBA': {'name': 'Bond Markets Unit European Composite Unit (EURCO)', 'flag': 'xxx'},
    'XBB': {'name': 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', 'flag': 'xxx'},
    'XBC': {'name': 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', 'flag': 'xxx'},
    'XBD': {'name': 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 'flag': 'xxx'},
    'XCD': {'name': 'East Caribbean Dollar', 'flag': 'xxx'},
    'XDR': {'name': 'SDR (Special Drawing Right)', 'flag': 'xxx'},
    'XOF': {'name': 'CFA Franc BCEAO', 'flag': 'xxx'},
    'XPD': {'name': 'Palladium', 'flag': 'xxx'},
    'XPF': {'name': 'CFP Franc', 'flag': 'xxx'},
    'XPT': {'name': 'Platinum', 'flag': 'xxx'},
    'XSU': {'name': 'Sucre', 'flag': 'xxx'},
    'XTS': {'name': 'Codes specifically reserved for testing purposes', 'flag': 'xxx'},
    'XUA': {'name': 'ADB Unit of Account', 'flag': 'xxx'},
    'XXX': {'name': 'The codes assigned for transactions where no currency is involved', 'flag': 'xxx'},
    'YER': {'name': 'Yemeni Rial', 'flag': 'xxx'},
    'ZAR': {'name': 'Rand', 'flag': '🇿🇦'},
    'ZMW': {'name': 'Zambian Kwacha', 'flag': 'xxx'},
    'ZWL': {'name': 'Zimbabwe Dollar', 'flag': 'xxx'},
  };



}
