name: moolax
description: "Moola X: A foreign currency converter for travelers"
version: 3.0.0+4

environment:
  sdk: ^3.8.0

dependencies:
  connectivity_plus: ^6.0.4
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  http: ^1.2.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  
dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
