name: moolax
description: "Moola X: A foreign currency converter for travelers"
version: 3.0.0+4

environment:
  sdk: ^3.0.0

dependencies:
  connectivity_plus: ^6.0.4
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  http: ^1.2.2
  in_app_purchase: ^3.2.0
  intl: ^0.19.0
  shared_preferences: ^2.3.1
  
dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
